name: 'allergan_ui_demo'
version: '1.0.0'
config-version: 2

profile: 'allergan_ui_demo'

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  allergan_ui_demo:
    staging:
      +materialized: view
    marts:
      +materialized: table