name: 'wizard_doc_demo'
version: '1.0.0'
config-version: 2

profile: 'wizard_doc_demo'

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  wizard_doc_demo:
    staging:
      +materialized: view
    marts:
      +materialized: table
